### ISSUE TITLE
Failed to start H2 connection

### ISSUE THREAD

**Issue by chrisatta** [esl/MongoosePush#196]
when run docker image:
docker run -h mongoosepush -p 8443:8443 -v `pwd`/priv:/opt/app/priv -e PUSH_HTTPS_CERTFILE="/opt/app/priv/ssl/rest_cert.pem"  -e PUSH_HTTPS_KEYFILE="/opt/app/priv/ssl/rest_key.pem"  -e PUSH_APNS_ENABLED=0 -it --rm mongooseim/mongoose-push:latest

i have this error:

, ...]]","what":"h2_connection_start","when":"2020-10-28T09:29:23.283"}
{"application":"sparrow","at":"Elixir.Sparrow.H2Worker.try_start_conn/3:568","domain":"fcm.googleapis.com","file":"lib/sparrow/h2_worker.ex","next_try_in":"5000","pid":"#PID<0.1875.0>","port":443,"reason":":nxdomain","severity":"warn","status":"error","text":"Failed to start H2 connection","tls_options":"[verify: :verify_peer, depth: 99, cacerts:

**Comment by pawlooss1** [comment]
`nxdomain` means that probably there's something wrong with DNS. Also, when I run the provided `docker run` command I didn't get such error. So if the issue was in deed with MongoosePush in some older version it is now resolved. I'll close the issue for now but if you'd encounter such issue again feel free to reopen it (with some more verbose data - this could help us).
