### ISSUE TITLE
FCM "notification" payload is sent but need "data" payload 

### ISSUE THREAD

**Issue by jaspreet-android** [esl/MongoosePush#29]
mongoosePush send FCM push with "notification" payload but it should be "data" payload so that app can handle notification when app is in background.

**Comment by rslota** [comment]
Hi @jaspreet-android ,

This is explained in the `REST API` section of the [README.md](https://github.com/esl/MongoosePush/blob/master/README.md). The user decides whether to send `alert`/`notification` or `data` payload. MongoosePush will construct based on that matching FCM/APNS payload.

**Comment by rslota** [comment]
This is also used by MongooseIM, according to [this](https://github.com/esl/MongooseIM/blob/master/doc/modules/mod_push_service_mongoosepush.md) documentation, mobile device can send additional `publish-options` in initial `enable` command (XEP-0357) in form of `<field var='silent'><value>true</value></field>` in order to make MongooseIM send `data` instead of `alert` to MongoosePush which will result in notification you are expecting. Stanza examples can be found [here](https://github.com/esl/MongooseIM/blob/master/doc/user-guide/Push-notifications.md).

**Comment by jaspreet-android** [comment]
Thank you. silent = true done the trick.Before I thought that just for APNS but its for both FCM and APNS.
