### ISSUE TITLE
error: pathspec 'fix_testing' did not match any file(s) known to git

### ISSUE THREAD

**Issue by Mo33n** [esl/MongoosePush#32]
[root@ivr MongoosePush]# MIX_ENV=prod mix do deps.get, compile, certs.dev, release
* Updating pigeon (https://github.com/rslota/pigeon.git)
* Updating maru (https://github.com/rslota/maru.git)
error: pathspec 'fix_testing' did not match any file(s) known to git.
** (Mix) Command "git --git-dir=.git checkout --quiet fix_testing" failed

**Comment by Mo33n** [comment]
I just saw the mix file of project. there was a tag mentioned "fix_testing".
But the tag is not available in maru repo, any help ?

**Comment by rslota** [comment]
Hi @Mo33n ,

To be honest I don't really know why there is an issue with fetching `maru`. The important thing to notice here, is that currently the reference is to the fork of `maru` - `rslota/maru`. The tag/branch `fix_testing` is available there. 

The change to the fork of `maru` was because of a bug that was fixed in this fork and we have waited for a merge of the fix to `maru's` mainstream. As far I can see, our PR is already merged, so you can change the `maru` reference to mainstream one as long as you ensure you are using version 0.12.0 or newer. I'll do that soon along with PR but it could take several days until this change will be merged to the master.

**Comment by Mo33n** [comment]
Yeap. it worked. Thanks

**Comment by rslota** [comment]
In case of further issues (current code is not compatible with new `maru` version), please use changes from #33 .

**Comment by Mo33n** [comment]
Okay , i got it , lets wait for the pull to get merged in main.
Thanks alot @rslota .

**Comment by Mo33n** [comment]
oky got the fix (e457bdc), Thanks.
