### ISSUE TITLE
distillery 1.3.3 RETIRED! (other) Custom commands are broken in this release

### ISSUE THREAD

**Issue by deadjdona** [esl/MongoosePush#39]
==> One or more direct or transitive dependencies are missing from :applications or :included_applications, they will not be included in the release:

    :parse_trans

    This can cause your application to fail at runtime. If you are sure that this is not an issue, you may ignore this warning.

**Comment by rslota** [comment]
Hi @deadjdona , 

What is the issue here? The logs that you have attached shows no problems at all. This warning is just a warning and we need to live with it, since `parse_trans` is indeed not used in runtime (it's needed for compilation only), hence there is no reason to list it in `:applications`.

**Comment by deadjdona** [comment]
The issue is in "distillery 1.3.3 RETIRED!" message on compile.
It increase my level of uncertainty to inappropriate level.

Thanks for PR!
